export const SET_USER_DATA = 'SET_USER_DATA';
export const CHANGE_VIEW_HOME = 'CHANGE_VIEW_HOME';
export const CHANGE_VIEW_TASKS = 'CHANGE_VIEW_TASKS';
export const CHANGE_VIEW_BUGS = 'CHANGE_VIEW_BUGS';
export const CHANGE_VIEW_BACKLOG = 'CHANGE_VIEW_BACKLOG';
